version: '3.8'

services:
  crm-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://crm_user:${POSTGRES_PASSWORD}@db:5432/crm_production
      - JWT_SECRET=${JWT_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - crm-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=crm_production
      - POSTGRES_USER=crm_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - crm-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - crm-app
    restart: unless-stopped
    networks:
      - crm-network

volumes:
  postgres_data:

networks:
  crm-network:
    driver: bridge



